---
id: lilo-20160501
base_name: lilo-20160501
tags:
- debian
presentation_date: 2016.5.1
version: 1.0.0
licenses: []
slideshare_id: lilo-20160501
speaker_deck_id: lilo-dot-linux-dot-or-dot-jp-from-wheezy-to-jessie
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :rd
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
